M48
; DRILL file {KiCad 6.0.9+dfsg-1} date Wed 25 Jan 2023 09:24:44 PM CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-25T21:24:44+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.9+dfsg-1
; #@! TF.FileFunction,Plated,2,4,Blind
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,Buried,ViaDrill
T1C0.200
%
G90
G05
T1
X117.225Y-174.925
X118.022Y-174.925
X121.025Y-178.125
X129.275Y-162.325
T0
M30
